apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gore-ingress # update
  labels:
    name: gore-ingress-dev # update
spec:
  ingressClassName: contour
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gore-svc # update
            port: 
              number: 80
