apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gore-ingress
  labels:
    name: gore-ingress-dev
  annotations:
    cert-manager.io/issuer: letsencrypt-production
    kubernetes.io/ingress.allow-http: "true"
spec:
  ingressClassName: contour
  rules:
  - host: gore2.gore.theworkpc.com #update
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gore-svc
            port: 
              number: 80
  tls:
    - hosts:
      - gore2.gore.theworkpc.com
      secretName: gore-tls
